### ISSUE TITLE
Cant get running

### ISSUE THREAD

**Issue by kingfenix** [comixed/comixed#1098]
I have tried the docker container un unraid, and you were right about the fix there, got it running, but it doesnt work. SO then I tried downloading the release jar file from git and running it under both windows and mac doesnt seem to do anything. 

I may be completely stupid here, but please for the love of god, how do I get this running and working?

TIA for any guidance, I tried the wiki no install instructions there, and google wasnt my friend today for this either :(

**Comment by kingfenix** [comment]
FYI, I have JDK 17.0.1 installed on both my windows and my mac computer

**Comment by kingfenix** [comment]
fm, every time I think I have something, I log in, and then the page changes to this state where no text exists and nothing is in the sidebar and nothing works or appears, mayvbe I should wait another year and try again, lol

**Comment by mcpierce** [comment]
@kingfenix We currently support only JDK 11. Anything higher than JDK 15 is going to be incompatible since Oracle has done something at the JDK 16 release that causes problems. 

Also, would you mind posting things like this to the [Comixed mailing list](https://www.freelists.org/list/comixed) rather than as bugs?

**Comment by mcpierce** [comment]
@kingfenix We currently support only JDK 11. Anything higher than JDK 15 is going to be incompatible since Oracle has done something at the JDK 16 release that causes problems. 

Also, would you mind posting things like this to the (Comixed mailing list](https://www.freelists.org/list/comixed) rather than as bugs?
