### ISSUE TITLE
Seperate Library Comics/Manga/Etc

### ISSUE THREAD

**Issue by mugenstylus1** [comixed/comixed#1312]
A feature to split the library up. so it could be 
/library/comics, 
/library/manga, 

and so on. so super important but did cross my mind.

**Comment by mcpierce** [comment]
@mugenstylus1 For the library, what would be the difference between a comic and a manga, for example? Are there any other types of entries that come to mind?

**Comment by mugenstylus1** [comment]
on the surface not too much, but i thought cause of the different styles in art work, and from separate countries. it be nice not to have to run two instances. This might also help encase you need to make a library for Adult Only Content.

**Comment by mcpierce** [comment]
@mugenstylus1 I like the idea of adult-only content, but don't see any way for CX to use that since it's not a reader app. I could see features like marking comics as having a certain reading style (left-to-right, right-to-left), and of marking content as mature, etc. as having no practical use unless a reader app used it to know how to render pages, or for blocking some content for children.

**Comment by mugenstylus1** [comment]
@mcpierce totally understand. I think maybe cause i use it with kavita, and i thought OPDS breakdown too. Maybe I am thinking too much about it.

**Comment by mcpierce** [comment]
@mugenstylus1 I don't think there's such a thing as thinking too much. You need to go through all your to find the ones you most want to do, eh?
