### ISSUE TITLE
Add Diabolik as a scraper

### ISSUE THREAD

**Issue by PoloDePoli** [comixed/comixed#1376]
**Is your feature request related to a problem? Please describe.**
ComicVine has limited coverage of italian comics

**Describe the solution you'd like**
I would love to see Diabolik  to be added as a scraper. (https://www.diabolik.it/)

**Describe alternatives you've considered**
Comicrack has a plugin for Diabolik - it used to work but the list refresh used to identify issues has failed in the last few months. It could provide a starting point.

**Comment by mcpierce** [comment]
@PoloDePoli Can you provide a link tot the ComicRack plugin for Diabolik?

**Comment by PoloDePoli** [comment]
https://drive.google.com/drive/folders/1X76QSVXrPRlqgFqKYlVxJl-ZxnVHf2An

Here are the links from the original author of the scripts it includes:
1) Bedetheque Scraper --> still works in comicrack
2) Bonelli Scraper --> for some comics (not all) as long as it is launched on a single issue it still works
3) Diabolik Scraper --> it works on the basis of a list mapping scraping, the list fails to update. It might still work if the list logic is updated
4) COA Inducks Scraper --> it works on the basis of a list mapping scraping, the list fails to update. It might still work if the list logic is updated

**Comment by mcpierce** [comment]
Adding the Diabolik CR plugin here for reference.
[Diabolik Scraper v1.9.crplugin.zip](https://github.com/comixed/comixed/files/9229402/Diabolik.Scraper.v1.9.crplugin.zip)

**Comment by mcpierce** [comment]
@PoloDePoli Hi, wanted to follow up on this. Your request hasn't been forgotten. The approach we've taken for adding new metadata scrapers is to make it so that developers can start a third-party project to provide those adapters, rather than making it a core feature of the CX project.

Please see [this email](https://www.freelists.org/post/comixed/The-future-of-metadata-adaptors-for-CX) from our mailing list for more details.
