### ISSUE TITLE
Reduce actions required to begin an import.

### ISSUE THREAD

**Issue by bareheiny** [comixed/comixed#152]
As a user, I would like to use as few actions as possible to import comics to the CX library.

This could be done by consolidating the with / without metadata buttons - and asking the user once, and remembering their preference.

This preference could be updated / reset via the admin panel.

Possibly a personal preference - but I'd only use the "with" metadata import during a large import, my more frequent smaller imports would default to the "without", as I strip all non image files from the comics prior to importing them.

**Comment by mcpierce** [comment]
I can see having the split button behavior present the previously chosen action when clicking on the parent, and using the dropdown to change that default behavior. Otherwise, I think it would just move the cumbersomeness elsewhere if we put the toggle on a different page that you'd have to go to in order to change the behavior. I thinking keeping all of the behavior on one page will require less moving around.

**Comment by bareheiny** [comment]
That works for me :)

Essentially I'm looking for ways to minimise the number of actions I need to take to do something, especially as using my fingers on a touch screen doesn't always give me the precision I need to select the appropriate action.

**Comment by bareheiny** [comment]
Closing this as it's essentially a duplicate of #148
