### ISSUE TITLE
Whitelist duplicated pages

### ISSUE THREAD

**Issue by bareheiny** [comixed/comixed#153]
When reviewing duplicate pages, I would like to be able to whitelist those that are acceptable as duplicates and have them excluded from the duplicate list.

This list should be able to be exported and shared with other users if desired.

**Comment by mcpierce** [comment]
Good feature idea! Adding it to the next release backlog.

**Comment by mcpierce** [comment]
@bareheiny Since I'm working on the duplicate page code, I was going to address this feature. But, the more I think about it, the more I think: do we really want to hide any duplicate pages from the list? I'm not sure a whitelist of "acceptable" pages serves any real purpose since the only thing you can do with a duplicate page is 1) look at the comics that contain it and 2) block/unblock the page.

**Comment by bareheiny** [comment]
I can't quite recall why I raised this feature request to be honest.

I suspect I was thinking of eventually blocking (then deleting) duplicated images - but was wanting a way to ignore acceptable duplicated pages.  Being able to exclude them from a view would reduce the amount of images I needed to inspect to decide if I should block / delete it or not.

**Comment by mcpierce** [comment]
@bareheiny Okay, so then what I'd like to do is close this until we have a clear benefit for such a feature, to keep the backlog simple.
