### ISSUE TITLE
Scraper errors out with no volumes found.

### ISSUE THREAD

**Issue by Uplinkpro** [comixed/comixed#2117]
**Describe The Bug**
After Scanning in a small amount of comics they process fine. When I go to scraper An error screen pops up No volumes found. I have the API key in the settings but I've also noticed the version of the metadata  adaptor is "Not Installed". Running the docker version I see no way to install or update this file.

**To Reproduce The Bug**
Steps to reproduce the behavior. Please be as complete as possible and describe the exact steps and values used to cause the error:
1. Start the Docker and Create new user account
1. Login and point folder to library and add API key to the scraper plugin
1. Scan in 1000 comics and wait for pages to hash check
1. After hash checking is complete go to Multi-Comic Scraper and attempt to scrape in a comic. 

**Expected Behavior**
Comics Scrape with updated data

**ComiXed Runtime Environment**

 - [ ] Windows
 - [X ] Linux (any distro)
 - [ ] MacOS
 - [X ] Docker (if so, please select the host OS)

**ComiXed Build Detail:**
Latest Docker Build

**Additional Context**
I have tested the Dockers connection to Comicvine and it connects properly and no matter what issue or volume of any comic its always the same. I have also checed the API key for spaces or errors however it works fine.

**Comment by mcpierce** [comment]
@Uplinkpro  Please include the reproducer steps so we can try to reproduce the error locally. I've updated the bug and restored that part of the bug report.

**Comment by Uplinkpro** [comment]
Updated with info requested

**Comment by mcpierce** [comment]
I don't see where the steps say any pages were selected for scraping. Did you at any point before going to the multi-scraping page go to a page like All Comics and select some issues and then click the "Scrape Comics" from the selected menu?

**Comment by Uplinkpro** [comment]
Nope I directly went to muli scrape, I just tried what you said and the same errors happened. All it did was take me to Muli-Comic scraping

**Comment by mcpierce** [comment]
That path (selecting comics, clicking on Scrape Comics from the context menu) is one I'm fixing for v2.2. The issue is related to how many comics are selected; i.e., the server is queueing those comics up for scraping while the browser is showing the page, and if there are a lot of comics selected then the queue isn't read when the page renders. If you select only a few (<50) the queue updates quickly. The workaround for that currently is to reload the multi-scraping page after maybe 10 seconds and the queue shows up correctly.
