### ISSUE TITLE
Library contents navigator - custom field(s).

### ISSUE THREAD

**Issue by bareheiny** [comixed/comixed#229]
First off, I'm liking the navigator pane...it's much more user friendly than the Contents tree.

To enhance it a little more, I would like to see another option (or two, or three) added - something along the lines of "Series Group".

The use case is this:  

I'm going to group related comics into a single custom series - for example I'll group the various Hellblazer / Constantine series and trades into a "Hellblazer" or similar group (related, I'll need to add a custom number as well to keep things in order).

When I use the library navigator, I want to be able to get to this series group - as it stands there are a number of distinct series that contain "Hellblazer", being able to get to them easily is almost essential.

Relies on #147

**Comment by mcpierce** [comment]
Thank you! It's going to require some reworking of the UX. Working on #207 exposed to me some fragility in how comics were being grouped for display. I'll be working on this tree more for the 0.6 release.

So, for this, we would have entries in the tree based on the keywords or custom fields values? I wonder, would we do better to have tagging and show a tag cloud to find comics; i.e., you tag comics with "Hellblazer" and then you can display them by looking at comics with that tag?

I think tagging, rather than adding some number of arbitrary fields, might be easier to implement since we could have it so there are any number of tags associated with a comic.

**Comment by bareheiny** [comment]
I think that would work...but...there would need to be a way to sort the disparate series and volumes appropriately as well.

Using Hellblazer, there are a number of tpbs and such...each tpb will (likely) be number 1 in that series - so sorting becomes an issue.

Mudding the water even more, I may have issues 1 through 50, a tpb that collects 51 to 57, a tpb that collects 58-61, and then issues 62 through 100 and so on.

What I need is a way to not only group everything together, but also indicate that issues 1-50, the two tps and issues 62-100 not only belong to the same collection...but also the same series and volume, and to specify the sort order.

These fields would also need to be exposed to the renaming process (when it's available)...as I'd be wanting to rename the entire collection in such a way that they could reside in the same folder, in numerical order (or maybe reading order if I went down that path).


I could approximate this type of functionality via SQL, or (if I had an OPDS compatible comic reader) reading lists....but not all users would be that comfortable tinkering with SQL and the back end.  Not to mention that CR has these types of fields pre-defined.


Apologies, this turned into a longer post that expected...probably fits better as a discussion in the mailing list!

**Comment by mcpierce** [comment]
I just created #231 to help with that; i.e., when series are displayed in the navigation tree each specific volume of a series is grouped separately.

So when viewing comics tagged with "farkle", you'd want to see something like:
 * Hellblazer (v????) [89 comics]
 * Hellblazer (TPB) [2]

Is that correct? 

**(edit)**

Instead of the above, I'd rather do:
 * Hellblazer (v????) [89 comics, 2 TPBs]

or just have it show 91 separate files for that series/volume set. I'd rather do the latter since that keeps the navigation tree useful but simple.

And, yeah, users shouldn't muck about editing the DB manually since that can lead to "nondeterministic behavior" and they'll void their warranty. 😄

**Comment by bareheiny** [comment]
The second option works for me - but the meat of it the issue is in the sorting and numbering.

In the navigation tree I'll be happy to see "Hellblazer (v????) [89 comics, 2 TPBs]", but when I got to the issues I'd like to see:

Hellblazer v1998 001
Hellblazer v1998 002
...
Hellblazer v1998 069
Hellblazer v1998 070
Hellblazer: Rake at the Gates of Hell v2014 001 _(collects issues 72-82)_
Hellblazer v1998 083
...
Hellblazer v1998 300
Constantine v2013 001
...
Constantine v2013 023
Constantine: The Hellblazer: Going Down v2016 001 _(collects issues 1-6)_
Constantine: The Hellblazer: The Art of the Deal v2016 001 _(collects 7-13)_
The Helllblazer v2016 001

and so on.  Not to mention trying to slot the various one-shots, annuals and specials in there!

note:  the text in italics is fyi only, I'm not expecting to see that in the navigation menu!

**Comment by mcpierce** [comment]
Oh, sorry, the tree won't show the individual issues for the different collections. The tree is just for getting to collections quickly. The issues themselves will show up in the comic window.

**Comment by bareheiny** [comment]
Now that you've said that, it's obvious that the navigation tree isn't the place for the numbering!

So your tagging idea would be a great start.  That would allow me to tag all those issues for Hellblazer and easily navigate to them.  After that I'd want a new way to flag the sort order and then sort them that way!

**Comment by mcpierce** [comment]
Closing this as relating to the old user interface (pre 0.8).
