### ISSUE TITLE
Include the volume when grouping comics.

### ISSUE THREAD

**Issue by mcpierce** [comixed/comixed#231]
Currently comics are managed on the frontend by series using only the name. This needs to include the volume as well, so that "Series 1 (v2000)" is differentiated from "Series 1 (v2015)".

**Comment by bareheiny** [comment]
Keep in mind that there may be "duplicate" volumes for a series.

For example Gen 13 has a 1994 mini-series, followed by a 81 issue series starting in 1994...so they both would be Gen 13 (v1994).

**Comment by mcpierce** [comment]
Ooh, that's an unexpected wrinkle. How would we differentiate two different series that have the same publisher, series and volume values? That is, without relying on CV data.

**Comment by bareheiny** [comment]
Ah...turns out that even CR just groups them together!

It hasn't caused me any problems because I use include the publication year and month in my file naming.  Before I started doing that, I'm sure I accidentally overwrote an issue or two of 1999s Batman Beyond - which also has a short mini-series and a longer series starting in the same year.

**Comment by bareheiny** [comment]
Maybe it'll come down to alerting the user that there appears to be duplicate issues (bases on series, volume and issue number) for the a series and volume, and asking for them to flag the order somehow?  Of course, doing that means the user would need to flag every comic in at least one of groups.
