### ISSUE TITLE
OPDS

### ISSUE THREAD

**Issue by Dunuin** [comixed/comixed#514]
Hi,

I wasn't able to find how to use/setup OPDS.
What is the URL used for the OPDS API?
And what port?

Some hints in the quickstart.md would be nice.

**Comment by mcpierce** [comment]
@Dunuin Thanks for bringing this up. The information is in our docs, but was in the wrong file (CONTRIBUTING.MD rather than QUICKSTART.md). I'm moving that over now. But here's the relevant portion:

## Reading Comics Remotely

You can read comics from your library using any comic reader that supports the [OPDS](https://opds.io/),
such as [Chunky Reader](http://chunkyreader.com/).

To allow your reader to access the library, you will need either the hostname or IP address for the computer
running ComiXed. So, for example, if that computers IP address is **192.168.1.29** then you would tell the
reader:

    Hostname: http://192.168.1.29:7171/opds-comics
    Username: [the username for your login]
    Password: [the password for your login]

Please note that some readers (such as Chunky) assume the **/opds** portion of the URL. SO if your reader
does not see a reading list, try removing **/opds** from the URL.

Then your reader should see, at least, a reading list named **All Comics**. This list will allow you to read
all comics in your library.

Future work will allow for different reading lists to be presented via OPDS. Please stay tuned for those
changes to arrive.

**Comment by mcpierce** [comment]
If the above answer and the code changes answer you question, please feel free to close this ticket.

**Comment by Dunuin** [comment]
Ok, Thanks.
