### ISSUE TITLE
LAUNCHING THE APP ON QNAS

### ISSUE THREAD

**Issue by nahoul** [comixed/comixed#583]
Hello,
I installed the app on my Qnap through the QnapClub repository, when i launch it, it opens a new tab to my NAS address with port 7171, but I get an error 192.168.1.112 refused to connect.

I don't see any way in my QNAS to configure it to connect.

**Comment by mcpierce** [comment]
@nahoul Thanks for bringing this to our attention!

I'm not familiar with Qnap. Does it run a Linux-based distribution as its operating system?

In your environment, is 192.168.1.112 the Qnas device that's running ComiXed? If so, then the error sounds like the firewall on the device is blocking any connections on port 7171. Are you able to open port 7171 on the Qnap device and then relaunch ComiXed and see if that fixes the issue?

**Comment by nahoul** [comment]
thanks for the reply
it is a QNAP NAS device. i do believe it runs a Linux based OS. here is the OS release info
NAME="QTS"
VERSION="4.5.1 (20201123)"
ID=qts
PRETTY_NAME="QTS 4.5.1 (20201123)"
VERSION_ID="4.5.1"

someone in the QNAS qnapclub community created a package of the app for the device (http://forum.qnapclub.fr/topic/11011-comixed/) . i have not installed a firewall on it. and every app I run on it seems to work fine. including ones that need a port to access on my web browser such as Plex, AirDCPP, Resolio Sync. this is the only app that seems to not work. 

i will check with the person who created the package in the community. this could be a config issue. the first challenge is to find where the app is installed after I putty to it :D

**Comment by mcpierce** [comment]
@nahoul Very cool, and a big thank you to the person who packaged things up! 💯

I downloaded the dpkg file and, when I have a chance, I can crack it open and look at it.

**Comment by nahoul** [comment]
cheers. Thanks

**Comment by tomdrakecanada** [comment]
I just wanted to add that I also have this issue with my QNAP TS-453Be. I used the TS-NASX86_64 version 0.7.1.2 and also tried the 0.6.3.0, still get the connection refused. You can't install the package without QJDK8, though I also installed QJDK14 after to see if that would help... still no luck.

In the meantime, starting to build my library in the Windows version and I'm assuming I can use export and then import when we solve the QNAP issue?

**Comment by mcpierce** [comment]
@tomdrakecanada @nahoul Have either of you reached out to or received a response from the package maintainer?

From my experience, when a system refuses connection to a port it's because the port is not opened due to a firewall rule. If the port were to timeout then I would think it's the case that the port is open but the ComiXed app, for whatever reason, wasn't running. But QNAP refusing the connection is something outside of CX's control: that's a firewall or configuration issue.

Can you both confirm that the package, once installed, is actually launching ComiXed?

Unfortunately, I can't find a way to extract the contents of the qpkg file on my laptop. So if someone could extract one (or point me to a repo with the packaging files, not the final product0 I'd be glad to look into it.

**Comment by SinisterStairs** [comment]
There's definitely bugs w/ the 0.7.1.2 qpkg.  I mentioned this to the maintainer a few weeks back:
http://forum.qnapclub.fr/topic/11011-comixed/?do=findComment&comment=46647
As packaged, the run scripts checks "if the comixed.jar exists, say the the JAR is missing and abort"; obviously, connection is refused since it's not even running.

As disappointing as that is, this issue can probably be closed because it's unrelated to ComiXed itself.

EDIT: Yes, QTS is QNAP's custom Linux distribution.  My TS-451 is:
<code>Linux [hostname] 4.14.24-qnap #1 SMP Tue Feb 2 01:48:26 CST 2021 x86_64 GNU/Linux</code>

**Comment by mcpierce** [comment]
@SinisterStairs Thanks for following up on this! I saw the thread on QNap's forums and replied there as well WRT the level of JDK needed. Closing this as invalid.

**Comment by SinisterStairs** [comment]
Hopefully commenting here won't re-open the issue:  A newer release of ComiXed was made for QTS (QNAP).  I have not tried it yet because of hardware issues, but I'm curious to see if they've fixed the QPKG.

**Comment by mcpierce** [comment]
@SinisterStairs No, it doesn't reopen the issue. 😄 

Do you have a way of contacting that maintainer to ask them, and invite them to respond here as well?
